version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: library-postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./library-webapp
    container_name: library-webapp
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: library_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./library-frontend
    container_name: library-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
